name: Build SeeMore

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up NabConfiguration JDK
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'adopt'

      - name: Check out NabConfiguration
        uses: actions/checkout@v2
        with:
          repository: froobynooby/nab-configuration

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Install NabConfiguration
        run: ./gradlew install

      - name: Set up SeeMore JDK
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Check out SeeMore
        uses: actions/checkout@v2

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Build SeeMore
        run: ./gradlew build

      - name: Archive SeeMore
        uses: actions/upload-artifact@v2
        with:
          path: build/libs/*.jar
          name: SeeMore
